# Generated by Django 5.2.1 on 2025-06-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_alter_review_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='userfollows',
            options={'ordering': ['followed_user__username', 'user__username']},
        ),
    ]
